### ISSUE TITLE
NEUTRONNNN

### ISSUE THREAD

**Issue by Verocter25** [NeutronForge/little-johns-1.20.6#1]
MAKE IT FOR 1.19.2 FABRIC AND MY WIFE IS YOURSS
in all seriousness please if you want make it for 1.19.2 I didn't know wherelse to request this 
It would be so awesome 🙏

**Comment by NeutronForge** [comment]
I’m really sorry (and REALLY late) but I won’t back port the mod at the current time since mojangs spaghetti code changes between major versions aren’t anything I want to worry about

**Comment by Verocter25** [comment]
Ah yeah that's fair
Still a great mod though!
